# Applied Machine Learning 2
## Course project          
                                                 Author: Diego Rodriguez
## Dense network
Finally, try with neural networks
- 1-layer dense network i.e. no hidden layer, just the input and output ones 
- 2-layer dense network i.e. one hidden layer


In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

# Load the npz file
base_dir = '/Users/rodriguezmod/Downloads/swissroads/'

with np.load(base_dir+'features.npz', allow_pickle=False) as npz_file: 
    # It's a dictionary-like object 
    print(list(npz_file.keys()))
    
    # Load the arrays    
    # Merging test and validation features data to use a cross-validation approach to model fitting.
    X_tr = np.concatenate((npz_file['train_features'], npz_file['validation_features']))
    X_tr_pixels = np.concatenate((npz_file['train_pixels'], npz_file['validation_pixels']))
    y_tr = np.concatenate((npz_file['train_labels'], npz_file['validation_labels']))
    # Reduce to 1-dim
    y_tr = np.argmax(y_tr, axis=1)

    X_te = npz_file['test_features']
    X_te_pixels = npz_file['test_pixels']
    y_te = npz_file['test_labels']
    # Reduce to 1-dim
    y_te = np.argmax(y_te, axis=1)

['train_features', 'validation_features', 'test_features', 'train_labels', 'validation_labels', 'test_labels', 'train_pixels', 'validation_pixels', 'test_pixels']


## 1-layer
1-layer dense network i.e. no hidden layer, just the input and output ones

In [2]:
# Import warnings, there are a lot verbosity due deprecated tensorflow modules
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import tensorflow as tf
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import activations
from tensorflow.keras import initializers

# Create model with no hidden layers
model_1l = Sequential()

# Input layer
model_1l.add(Dense(
    units=216, activation=activations.relu, input_dim=1280,
    kernel_initializer=initializers.VarianceScaling(scale=2.0, seed=0)))

# Output layer
model_1l.add(Dense(
    units=6, activation=activations.softmax,
    kernel_initializer=initializers.VarianceScaling(scale=1.0, seed=0)))

# Print network summary
model_1l.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 216)               276696    
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 1302      
Total params: 277,998
Trainable params: 277,998
Non-trainable params: 0
_________________________________________________________________


In [3]:
from tensorflow.keras import optimizers

# Define loss function, optimizer and metrics to track during training
model_1l.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['acc'])

In [4]:
# Fit model
history_1l = model_1l.fit(
    x=X_tr, y=y_tr,
    validation_split=0.8, batch_size=10, epochs=30,
    shuffle=True
)

Train on 83 samples, validate on 336 samples
Epoch 1/30
83/83 [==============================] - 0s 4ms/sample - loss: 1.3271 - acc: 0.5663 - val_loss: 0.7623 - val_acc: 0.7619
Epoch 2/30
83/83 [==============================] - 0s 862us/sample - loss: 0.3880 - acc: 0.8795 - val_loss: 0.3875 - val_acc: 0.8601
Epoch 3/30
83/83 [==============================] - 0s 835us/sample - loss: 0.1022 - acc: 0.9639 - val_loss: 0.3363 - val_acc: 0.8839
Epoch 4/30
83/83 [==============================] - 0s 917us/sample - loss: 0.0467 - acc: 0.9880 - val_loss: 0.3053 - val_acc: 0.8839
Epoch 5/30
83/83 [==============================] - 0s 923us/sample - loss: 0.0202 - acc: 1.0000 - val_loss: 0.2783 - val_acc: 0.8810
Epoch 6/30
83/83 [==============================] - 0s 828us/sample - loss: 0.0189 - acc: 1.0000 - val_loss: 0.2984 - val_acc: 0.8929
Epoch 7/30
83/83 [==============================] - 0s 829us/sample - loss: 0.0087 - acc: 1.0000 - val_loss: 0.3859 - val_acc: 0.8571
Epoch 8/30
83/83 [=

In [5]:
# Evaluate on train set
(test_loss_tr, test_accuracy_tr) = model_1l.evaluate(X_tr, y_tr, batch_size=10)

# Evaluate on test set
(test_loss_te, test_accuracy_te) = model_1l.evaluate(X_te, y_te, batch_size=10)

print('Train loss: {:.2f}'.format(test_loss_tr))
print('Train accuracy: {:.1f}%'.format(100*test_accuracy_tr)) 

print('Test loss: {:.2f}'.format(test_loss_te))
print('Test accuracy: {:.1f}%'.format(100*test_accuracy_te)) 

50/50 [==============================] - 0s 151us/sample - loss: 0.4578 - acc: 0.8800
Train loss: 0.26
Train accuracy: 90.9%
Test loss: 0.46
Test accuracy: 88.0%


## 2-layer
2-layer dense network i.e. one hidden layer

In [6]:
# Create model with one hidden layer
model_2l = Sequential()

# Input layer
model_2l.add(Dense(
    units=216, activation=activations.relu, input_dim=1280,
    kernel_initializer=initializers.VarianceScaling(scale=2.0, seed=0)))

# One hidden layer
model_2l.add(Dense(
    units=216*2, activation=activations.relu,
    kernel_initializer=initializers.VarianceScaling(scale=2.0, seed=0)))

# Output layer
model_2l.add(Dense(
    units=6, activation=activations.softmax,
    kernel_initializer=initializers.VarianceScaling(scale=1.0, seed=0)))

# Print network summary
model_2l.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 216)               276696    
_________________________________________________________________
dense_3 (Dense)              (None, 432)               93744     
_________________________________________________________________
dense_4 (Dense)              (None, 6)                 2598      
Total params: 373,038
Trainable params: 373,038
Non-trainable params: 0
_________________________________________________________________


In [7]:
from tensorflow.keras import optimizers

# Define loss function, optimizer and metrics to track during training
model_2l.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['acc'])

In [8]:
# Fit model
history_2l = model_2l.fit(
    x=X_tr, y=y_tr,
    validation_split=0.8, batch_size=10, epochs=30,
    shuffle=True
)

Train on 83 samples, validate on 336 samples
Epoch 1/30
83/83 [==============================] - 0s 5ms/sample - loss: 1.2346 - acc: 0.5542 - val_loss: 0.5669 - val_acc: 0.8095
Epoch 2/30
83/83 [==============================] - 0s 1ms/sample - loss: 0.1830 - acc: 0.9639 - val_loss: 0.3277 - val_acc: 0.8512
Epoch 3/30
83/83 [==============================] - 0s 1ms/sample - loss: 0.0627 - acc: 0.9759 - val_loss: 0.3624 - val_acc: 0.8690
Epoch 4/30
83/83 [==============================] - 0s 1ms/sample - loss: 0.0154 - acc: 1.0000 - val_loss: 0.3831 - val_acc: 0.8542
Epoch 5/30
83/83 [==============================] - 0s 989us/sample - loss: 0.0077 - acc: 1.0000 - val_loss: 0.2965 - val_acc: 0.8929
Epoch 6/30
83/83 [==============================] - 0s 995us/sample - loss: 0.0028 - acc: 1.0000 - val_loss: 0.3160 - val_acc: 0.8958
Epoch 7/30
83/83 [==============================] - 0s 1ms/sample - loss: 0.0020 - acc: 1.0000 - val_loss: 0.3298 - val_acc: 0.8869
Epoch 8/30
83/83 [=========

In [9]:
# Evaluate on train set
(test_loss_tr, test_accuracy_tr) = model_2l.evaluate(X_tr, y_tr, batch_size=10)

# Evaluate on test set
(test_loss_te, test_accuracy_te) = model_2l.evaluate(X_te, y_te, batch_size=10)

print('Train loss: {:.2f}'.format(test_loss_tr))
print('Train accuracy: {:.1f}%'.format(100*test_accuracy_tr)) 

print('Test loss: {:.2f}'.format(test_loss_te))
print('Test accuracy: {:.1f}%'.format(100*test_accuracy_te)) 

50/50 [==============================] - 0s 185us/sample - loss: 0.3621 - acc: 0.9000
Train loss: 0.31
Train accuracy: 90.2%
Test loss: 0.36
Test accuracy: 90.0%


After fitting 1-layer dense network (no hidden layer) model an accuracy value of **88.0%** is obtained, which is a good value. With a 2-layer dense network (one hidden layer) model, an accuracy value of **90.0%** is obtained, it is a really good value, it is a bit better than the one obtained previously. 